export const custGroupData = [
  "L&T GROUP - EM",
  "AMEX - BFSI",
  "Rathbone",
  "P&G",
  "Harvard Business Sch",
  "AMEX - TRAVEL",
  "GE",
  "Microsoft-CSPP",
  "ComputerServices Inc",
  "CISCO",
  "VEOLIA",
  "INGRAM MICRO",
  "LâOREAL",
  "TRAVELERS",
  "ABSA",
  "HONDA",
  "CITIZENS BANK",
  "VATTENFALL",
  "JOHNSON & JOHNSON",
  "NAVISTAR",
  "VIACOM - EM",
  "WORLD BANK GROUP",
  "GALLAGHER",
  "CITIGROUP",
  "STAR INDIA",
  "TAMRO OYJ- NR",
  "FAIRFAX",
  "CHEVRON",
  "MMC",
  "AMERICAN AXLE",
  "PBF ENERGY",
  "OTIS",
  "POCLAIN",
  "CARRIER",
  "CATERPILLAR INC",
  "TRYG",
  "KMD A/S",
  "PETROGAS",
  "COX & KINGS",
  "ATTENDS HEALTHCARE A",
  "RELIANT",
  "BANK OF BARODA-EM",
  "QATAR AIRWAYS",
  "SONY",
  "ASG GROUP",
  "PETRO RABIGH",
  "BB&T INSURANCE HOLDI",
  "ASSUREDPARTNERS",
  "HORACE MANN",
  "HD SUPPLY",
  "PARAMOUNT",
  "STANDARD CHARTERED B",
  "CSRS",
  "AMERICAN BUREAU OF S",
  "SUPERGROS",
  "PROS â CMT",
  "API Group Inc",
  "RESONATE SOLUTIONS P",
  "KOMATSU",
  "AJINOMOTO",
  "PHILLIPS 66",
  "COP",
  "FITCH RATINGS - EU",
  "SCANIA",
  "NETS HOLDINGS",
  "NORDEA",
  "CBDT",
  "UTC GROUP",
  "CROWLEY MARITIME",
  "HDFC",
  "Warner Bros. Discove",
  "COLOPLAST",
  "FLOWSERVE - MFG",
  "ATI ALLVAC LTD",
  "MP POWER",
  "CICP",
  "FLUOR INC",
  "PRINCIPAL GROUP",
  "UNIVERSAL MUSIC GROU",
  "CANON",
  "NOMURA",
  "HARYANA GENCO",
  "MUNICH RE",
  "HSBC",
  "BNP-EU",
  "CIRCOR",
  "OSHKOSH",
  "LIBERTY GROUP",
  "PKGB",
  "ANIXTER",
  "EATON",
  "RESMED",
  "SBI LIFE INSURANCE",
  "INFINEON",
  "NEXPERIA",
  "TEREX",
  "JOHNSON CONTROLS",
  "PARSONS BRINCKERHOFF",
  "NET MAGIC",
  "INTERNATIONAL MONETA",
  "SIEMENS WIND POWER A",
  "HAZIRA LNG PRIVATE L",
  "ACCUDYNE INDUSTRIES",
  "NYNAS AB",
  "AIRBUS",
  "BREAD FINANCIAL",
  "MAX HAMBURGER",
  "COLGATE PALMOLIVE",
  "INTUITIVE SURGICALS",
  "DEXCOM",
  "BAJAJ ALLIANZ",
  "NXP",
  "VITAMIX",
  "INTERIOR SPECIALISTS",
  "JEFFERIES LLC",
  "SCHNEIDER ELECTRIC â",
  "EXPERIAN CREDIT INFO",
  "TASNEE",
  "ABBOTT",
  "DISCOVERY LIMITED",
  "LORD ABBETT & CO.",
  "FIRSTRAND BANK",
  "BROADRIDGE FINANCIAL",
  "ONEMAIN SOLUTIONS",
  "APTTUS",
  "TAYLOR COMMERCIAL FO",
  "VELLIV",
  "UN ICC",
  "COPPERPOINT INSURANC",
  "INSURANCE COMPANY OF",
  "W. R. BERKLEY CORPOR",
  "RISKONNECT",
  "AREVA",
  "AICTE",
  "MICROSOFT",
  "CLARIOS",
  "CARESTREAM",
  "ACORD",
  "SOCIÃTÃ BIC S.A",
  "CHUBB INA HOLDINGS",
  "PIH",
  "NASSAU RE",
  "SECURITAS USA",
  "CMA CGM",
  "NOV",
  "MYLAN",
  "BLACK & VEATCH",
  "GENRE",
  "COLAS",
  "BOSTON SCIENTIFIC",
  "UP GENCO",
  "ELKJÃP",
  "HORIZON MEDIA",
  "HEARST",
  "IDBI",
  "PUBLIC TRANSPORT CO",
  "CASIO",
  "MINISTRY OF STATISTI",
  "SP GLOBAL",
  "ADVANCED ELECTRONICS",
  "WOLTERS KLUWER",
  "CATALENT",
  "DCP MIDSTREAM",
  "ERNST & YOUNG GLOBAL",
  "EDGEWOOD PARTNERS IN",
  "LAFARGE",
  "OKQ8 AB",
  "VIZIENT",
  "ASI",
  "INJAZAT",
  "MINISTRY OF CORPORAT",
  "CORE & MAIN",
  "MICROSOFT-MFG",
  "YASREF",
  "OLAM",
  "SCHINDLER HOLDING LT",
  "DEUTSCHE TELEKOM",
  "YOKOGAWA",
  "PROTECTIVE INSURANCE",
  "CONDE NAST",
  "CHEVRON PHILLIPS",
  "HALLIBURTON",
  "O9",
  "BUREAU VERITAS",
  "ONGC",
  "SOCIETE GENERALE",
  "BUILDERS MUTUAL",
  "EVERSOURCE ENERGY",
  "HONEYWELL",
  "ROCKWOOL GROUP",
  "WEATHERFORD",
  "CENTURION",
  "INSURITY",
  "INDUSIND BANK",
  "IRVINE COMPANY",
  "SERVICENOW",
  "MSCI INC",
  "AFLAC",
  "YIL",
  "M&C RESERVATIONS SER",
  "NEXANT INC",
  "LUFKIN INDUSTRIES, L",
  "CIRCLE K",
  "WHITECAP",
  "Angola LNG",
  "QATAR FOUNDATION",
  "MAERSK - OG",
  "VOLKSWAGEN GROUP OF",
  "CGG",
  "BROWN & BROWN INSURA",
  "UNILEVER",
  "DISNEY WORLDWIDE",
  "AL RAJHI BANK",
  "SIGNIFY",
  "YORKSHIRE WATER",
  "HINDALCO INDUSTRIES",
  "EXXONMOBIL",
  "CIGNA",
  "REV GROUP",
  "SOMPO INTERNATIONAL",
  "AMAZON",
  "HOWDEN UK",
  "SIEMENS SOFTWARE FR.",
  "PHARMA INFORMATION A",
  "THALES",
  "COMPASS",
  "FLIPKART",
  "FINANCIAL RULER",
  "TTMS",
  "REPUBLIC TV",
  "WORXOGO",
  "VOX MEDIA",
  "EIGENRISK",
  "DEVEN SOFTWARE",
  "SUMMA LINGUAE",
  "HONEYWELL PROCESS SO",
  "RIYAD BANK",
  "PARKER HANNIFIN CORP",
  "CHARLES STANLEY",
  "BAKELITE",
  "ENI",
  "ICICI BANK",
  "LINCOLN",
  "FIDELITY INTERNATION",
  "GE ENERGY",
  "ECLINICALHEALTH LIMI",
  "VANTAGE GROUP HOLDIN",
  "CRITEO",
  "BANK OF CHINA",
  "HUSQVARNA",
  "GTPL HATHWAY",
  "DANFOSS",
  "RCU",
  "CREDIT CORP GROUP AU",
  "OMYA",
  "CLUB CAR",
  "TECHNIPFMC_AO",
  "WORLD VISION CANADA",
  "ROLLS ROYCE",
  "ULTRAGENYX PHARMACEU",
  "SADARA CHEMICAL COMP",
  "QATAR ELECTRICITY &",
  "BANK WINDHOEK",
  "PROXYMITY",
  "USV PVT. LIMITED",
  "PORTLAND GENERAL ELE",
  "BULLA DAIRY FOODS",
  "VEECO",
  "SRS DISTRIBUTION",
  "CADENTTV",
  "OMAN INSURANCE",
  "EPSILON",
  "CHRISTIEâS",
  "BOSCH",
  "INVESCO",
  "GENERALI",
  "UTICA NATIONAL INSUR",
  "GALAXE",
  "CUSCAL",
  "BANFIELD PET HOSPITA",
  "WESTPAC BANKING CORP",
  "DSV",
  "ARIA SYSTEMS INC",
  "CAMPBELL FOODS",
  "RANPAK",
  "CBRE",
  "SELECTIVE INSURANCE",
  "ENSTAR",
  "ZIMPLISTIC PRIVATE L",
  "HOIST FINANCE",
  "SANTANDER GROUP - BF",
  "PERPETUAL SOLUTIONS",
  "GOLDENSOURCE INTERNA",
  "BANK OF INDIA",
  "NATIONAL HEALTH AUTH",
  "VMWARE",
  "CALIENT TECHNOLOGIES",
  "BUNDUQ",
  "HEWLETT PACKARD ENTE",
  "NEOM",
  "MERCK",
  "ENGIE",
  "THERMO FISHER SCIENT",
  "SINGAPORE PRESS HOLD",
  "ACI WORLDWIDE CORP",
  "FIRST ABU DHABI BANK",
  "INNOVEO AG",
  "ZS ASSOCIATES INDIA",
  "COMPASS USA",
  "SATORP",
  "BLACKLINE SAFETY COR",
  "UNHCR",
  "NATIONWIDE INSURANCE",
  "WILLIS TOWER WATSON",
  "ALLSTATE INSURANCE C",
  "GOOGLE",
  "LINDE AG",
  "GLOBAL INDEMNITY GRO",
  "MUSIC TRIBE",
  "INTERNATIONAL FLAVOR",
  "AMBA",
  "North Oil Company",
  "KPMG - CMT",
  "BREMBO",
  "SAUDI ARABIAN BRITIS",
  "SOONER",
  "APTIV",
  "ADVANCED PETROCHEMIC",
  "NBC UNIVERSAL",
  "MARATHON PETROLEUM",
  "Metasphere",
  "WOODSTOCK STERILE SO",
  "MODEL N",
  "BLOCKGRAPH LLC",
  "INTACT FINANCIAL GRO",
  "TILL PAYMENT",
  "HMS HOST",
  "NAVIGATORS GROUP INC",
  "ESSAR OIL UK",
  "Apex Services Partne",
  "CENTRALSQUARE TECHNO",
  "BANNER HEALTH",
  "DGS DENMARK",
  "Old Republic Insuran",
  "CHEMICAL ABSTRACT SO",
  "FLSMIDTH INDIA",
  "Chobani",
  "SAUDI ENTERTAINMENT",
  "AXEL JOHNSON INTERNA",
  "CENTRAL COAST COUNCI",
  "Hitachi Vantara",
  "Qatar Aluminium",
  "Lease Plan India Pri",
  "FORD MOTOR COMPANY",
  "Mahanagar Gas Limite",
  "Ahli Bank QSC",
  "CONVO RELAY",
  "SAUDI ARAMCO AFFILIA",
  "PFIZER",
  "NMS Labs",
  "SCHNEIDER ENTERPRISE",
  "KEURIG GREEN MOUNTAI",
  "Maverick Natural Res",
  "CAPSPECIALTY INSURAN",
  "Nektar Therapeutics",
  "Tawuniya",
  "Farmer Brothers Comp",
  "LTFS-BFS",
  "CITY NATIONAL BANK",
  "Charles Taylor",
  "ROSHN REAL ESTATE CO",
  "Health Innovation Pl",
  "H.W. KAUFMAN",
  "BP AMERICA PRODUCTIO",
  "THE J.G. WENTWORTH C",
  "IEEE",
  "ON SEMICONDUCTOR COR",
  "Excelitas",
  "SSLR (Govt of Karnat",
  "TARGUS",
  "KEHE DISTRIBUTORS",
  "Bitt Inc.",
  "Ãssur",
  "GD Energy Products",
  "REGAL REXNORD",
  "Arch Insurance Inc",
  "3D Systems",
  "NYU Edutech",
  "KOMATSU NORTHAMERICA",
  "ORCHID UNDERWRITERS",
  "LOCKTON COMPANIES IN",
  "GSK CPG",
  "Adherehealth",
  "LP Corp",
  "SpartanNash",
  "Ally Financials Inc",
  "SITA",
  "Boston Consulting",
  "Bose Corporation",
  "Celeno Communication",
  "Dell International",
  "Deloitte Consulting",
  "ANZ",
  "Emeritus",
  "ZUELLIG PHARMA",
  "Astra Zeneca",
  "Zoll",
  "Messer LLC",
  "ATLAS COPCO",
  "Nokia- ND",
  "Zones LLC",
  "Opsera_Inc",
  "Veritas",
  "ADIDAS",
  "Atotech",
  "Sophos Limited",
  "Pacific Life",
  "AVVO",
  "Marriott Ownership",
  "Sabre Inc.",
  "Sinch AB",
  "SENNHEISER",
  "McAfee",
  "Valmont Industries,",
  "AOL",
  "Philips Electronics",
  "BIGBASKET",
  "TITAN COMPANY LTD",
  "Ultra TechCement Ltd",
  "BBC",
  "Catalina",
  "BMW India Pvt Ltd",
  "AAMC",
  "Southwest Airlines",
  "7-Eleven",
  "Continental AG",
  "DeLaval",
  "NSE",
  "Marriott Internation",
  "Cargill",
  "Imperial Brands",
  "Akzo Nobel",
  "Carl Zeiss",
  "DHL Parcel",
  "Lookout",
  "INTEL",
  "DOVER CORPORATION",
  "Informatica",
  "Dubai Holding",
  "Ecolab",
  "Toshiba Carrier Corp",
  "LUCID MOTORS",
  "Fullerton",
  "Icertis",
  "Mentor Graphics Corp",
  "Lyve Minds",
  "Baptist Health",
  "Lufthansa Group",
  "AMADEUS",
  "Expedia Inc",
  "Knauf",
  "UNITED HEALTH-AA",
  "Genesys",
  "GRANT THORNTON (GTUS",
  "Informa",
  "TELEGRAPH MEDIA",
  "CSG Systems",
  "CADENCE",
  "Endurance Int'l",
  "Ericsson India",
  "Nordex SE",
  "HealthStream",
  "TPMG -Kaiser Permant",
  "Thryve Digital_Heal",
  "United Urology Group",
  "Managed Markets, LLC",
  "Everside Health",
  "COPE Healthcare",
  "KELLOGG'S",
  "MSC INDUSTRIAL",
  "Bissell",
  "British Sugar plc",
  "NPS",
  "TASEC",
  "ELECTRONIC ARTS INC.",
  "Telia",
  "AVIS BUDGET GROUP",
  "Hilton Resorts Corp",
  "WestJet",
  "Shake Shack",
  "DHL Express US",
  "NSDL",
  "TVS MOTOR COMPANY",
  "Delta Air Lines",
  "KOHLER",
  "Staples",
  "VOLVO GROUP",
  "Bharti Airtel Ltd",
  "IIIT",
  "Strata Manufacturing",
  "NV BEKAERT SA",
  "Ocado Innovation Ltd",
  "American Red Cross",
  "REALOGY",
  "LINCOLN-BI",
  "RECKITT BENCKISER-UI",
  "ALLEGIANT TRAVEL Co",
  "Sandvik",
  "FREESCALE SEMICONDUC",
  "Salesforce",
  "DSG Retail",
  "HINDUSTAN COCA-COLA",
  "Penn National Insura",
  "Decision Research Co",
  "General Atlantic",
  "Harris Associates LP",
  "TOYOTA MOTOR",
  "Flowbird Group",
  "British American Tob",
  "Newcrest Services Pt",
  "ELC Beauty",
  "PEPSICO - EU",
  "Dyson Technology Ltd",
  "Molnlycke",
  "Eveready Battery",
  "OnProcess Technology",
  "Exertis (UK) Limited",
  "Peterson Holding Co.",
  "LINK GROUP",
  "GameStop",
  "Infinite Electronics",
  "First Citizens Bank",
  "STARR INSURANCE",
  "THE HARTFORD",
  "DUCK CREEK TECHNOLOG",
  "EarlyWarning Service",
  "Hamilton Capital",
  "Sapiens Americas Cor",
  "FCCI Insurance Group",
  "Woodruff Sawyer",
  "SYNOVUS FINANCIAL CO",
  "SILICON VALLEY BANK",
  "Global Payments",
  "Jill Acquisition LLC",
  "Gunnebo AB",
  "Soho House",
  "MONDELEZ GLOBAL LLC_",
  "Metro Systems",
  "Teachers Federal",
  "Bank of America",
  "Sketchers U.S.A.Inc",
  "TOMTOM INTERNATIONAL",
  "GARMIN LTD - BT",
  "Sonos, Inc",
  "GS1 US Inc.",
  "Flowers Foods",
  "Western Asset Manage",
  "VoyaServicesCompany",
  "Newell Brands",
  "MORSCO, Inc",
  "GREAT AMERICAN INSUR",
  "LTTS GOGO LLC",
  "Brambles",
  "Pacific Speciality",
  "NFUM",
  "The Ford Foundation",
  "HOMESITE GROUP",
  "DUBAI COURTS",
  "BAYER INFORMATION",
  "SmileDirectClub",
  "TMP WORLDWIDE",
  "Granicus",
  "Flydubai",
  "INFRAHEDGE LTD",
  "Bridgeweave",
  "JP Morgan",
  "Hellenic Bank",
  "Alrajhi Takaful(ART)",
  "Louisiana Cat",
  "Colonial First State",
  "NEWBURY CORP",
  "THE CARLYLE GROUP",
  "Aspen Insurance",
  "SSP Financing",
  "Manufacturers Bank",
  "PineBridge",
  "Texas Capital Bank",
  "Orica Limited",
  "Equifax Inc",
  "CAPS",
  "Booking.com B.V.",
  "Inigo Limited",
  "DBS BANK LTD",
  "Console Pty Ltd",
  "IAG-ANZ",
  "Cypres Semiconductor",
  "Conversant Software",
  "Autodesk, Inc.",
  "Vitech Systems Sub",
  "MacArthur Foundation",
  "Carsales.com Ltd",
  "Xerox Business Servs",
  "Ekaterra Global",
  "Dairy Farm",
  "Pendal Group",
  "Shiftkey LLC",
  "Dialog Semiconductor",
  "Franklin Madison",
  "ETIHAD AIRWAYS",
  "Aberdeen Asset Mgmt",
  "BORGWARNER INC",
  "PANASONIC MARKETING",
  "Phyplus - BT",
  "Doctors company",
  "Slide Insurance, Inc",
  "TMNA SERVICES  LLC",
  "CAM Industrial solut",
  "Trophy Foods",
  "SingTel Global",
  "FISERV",
  "Bose Professional Co",
  "ZeroNorth",
  "BUILDERS FIRSTSOURCE",
  "OVERSEA-CHINESE BANK",
  "The Rig",
  "ADITYA BIRLA",
  "National Water Compa",
  "AVERY DENNISON",
  "Prudential BSN Takaf",
  "Konica Minolta Busin",
  "CWT Global",
  "ISS WORLD",
  "BURNS & MCDONNELL",
  "Heineken USA",
  "Rua AlMadinah Holdin",
  "XELLIA PHARMACEUTICA",
  "EstÃ©e Lauder UK",
  "NEWS CORP",
  "Western Union",
  "AESOP",
  "ATRIUM UNDERWRITERS",
  "CAE",
  "MAJESCO US",
  "ARENCO",
  "Baystate Health",
  "Silicon Labs",
  "EMERGENT BIOSOLUTION",
  "Wesfarmers group",
  "ACCELERANT",
  "Franklin Templeton",
  "The Key",
  "DS Smith",
  "CrossCover Insurance",
  "Brambles UK",
  "Waymark Infotech (Pt",
  "GoDaddy Inc",
  "Dentons US LLP",
  "LENOVO",
  "THE HOME DEPOT",
  "EDALL SYSTEMS AND SE",
  "Worldwide Express",
  "Covermore Insurance",
  "INGERSOLL RAND",
  "KOMATSU- AU",
  "Claireâs Stores Inc",
  "CBRE UK",
  "Sentiss Pharma",
  "Safran",
  "SBLI Insurance compa",
  "Sony Pictures",
  "DGDA",
  "Shell-LTTS",
  "Grow Inc.",
  "Integra Life Science",
  "Yale University",
  "Enbridge",
  "Puget Sound Energy",
  "BAUER Engineering In",
  "TE Connectivity",
  "Curia Global",
  "CREDIT AGRICOLE",
  "Ooredoo Qatar",
  "The Giorgi Companies",
  "Liberty Steel Group",
  "Saudi Commission for",
  "Winslow Constructors",
  "Qiddiya",
  "Magna International",
  "INGEVITY",
  "Blue Cross",
  "Ãlandsbanken",
  "Entain",
  "LTTS - Gemalto",
  "Stonegate Group",
  "Sparebanken 1 Forsik",
  "Liberty Mutual Holdi",
  "Fanatics",
  "Aptia Group Limited",
  "Air Products",
  "Hitech Shared Servic",
  "Colonial Pipeline",
  "CALPINE CORPORATION",
  "Stryker",
  "IFFCO International",
  "JP Morgan SE - Londo",
  "EIG PARTNERS",
  "IBM INDIA PVT LTD",
  "Banque Raiffeisen S.",
  "Mirabaud",
  "Tunisian Foreign Ban",
  "Chaabi",
  "Temenos",
  "Havin Bank",
  "BEA International",
  "FAB",
  "Dalenys",
  "Skipton",
  "SociÃ©tÃ© GÃ©nÃ©rale",
  "Edmond De",
  "BIL",
  "Swissquote Bank",
  "Banque Raiffeisen So",
  "Caixa",
  "Rakuten",
  "JPMC",
  "DNB",
  "Julius Baer - EU",
  "Commerzbank",
  "BGL BNP PARIBAS",
  "Banca March",
  "Quintet",
  "ABLV",
  "Bank Lombard Odier &",
  "KomerÄnÃ­ banka",
  "St.George - USS",
  "Dubai Properties",
  "Fiberlink Software",
  "SAP-MH",
  "Shenzhen Goodix",
  "Option Care",
  "Shanghai ZCAN Microe",
  "Jaguar Landrover",
  "ROYAL & SUN ALLIANCE",
  "Jet Privilege",
  "Synchrony Financial",
  "citizenM",
  "AMAZON - BT",
  "Gogo LLC",
  "RoyalCaribbeanCruise",
  "Citrix",
  "WorkFusion, Inc..",
  "Mer Solutions Gmbh",
  "WASL",
  "Culina Group Limited",
  "Texas Instruments",
  "DELPHI_TCI",
  "Caversham",
  "Kimberly - Clark",
  "PI - Partners, LLC",
  "Workforce Logiq",
  "UBS",
  "CIMB",
  "TMBThanachart Bank P",
  "Kiatnakin Phatra Sec",
  "AGORA DEALER SERVICE",
  "EMPIRE LIFE",
  "BMO",
  "SSQ SOCIETE",
  "BNYM",
  "CRIS-RAILWAYS",
  "The Chamberlain Grou",
  "COFOMO INC.",
  "INVENSYS",
  "CO-OPERATORS LIFE IN",
  "CIBC MELLON",
  "EDGEPOINT WEALTH MAN",
  "FONDS DE SOLIDARITE",
  "FIERA",
  "GWL",
  "MONEY SERVICES INC",
  "RBC",
  "CHRYSLER GROUP LLC",
  "FIU",
  "Foot Locker",
  "FULTON HOGAN",
  "DESJARDINS",
  "ICF",
  "ITEANIX",
  "AGF",
  "BMO HARRIS",
  "DATACORE",
  "EQUITABLE LIFE CANAD",
  "MONTRUSCO BOLTON INV",
  "MACKENZIE FINANCIAL",
  "PHILIPS HAGER & NORT",
  "TD BANK",
  "IVARI",
  "TREZ CAPITAL FUND MA",
  "WAWANESA",
  "KUWAIT OIL COMPANY",
  "KYOSAN",
  "ORDRS Inc.",
  "EROS INTERNATIONAL",
  "Planar Investments P",
  "Ready Networks",
  "UX Holdings",
  "MICROSOFT - EM",
  "MINISTRY OF HOME AFF",
  "SOJITZ CORPORATION",
  "PERCEPT SOLUTIONS PT",
  "RVNL",
  "RBI",
  "SAP â MFG",
  "WALMART",
  "NATWEST",
  "AIB",
  "THE CAPITAL GROUP CO",
  "TOPHAT",
  "TUTICORIN",
];

export const sbuData = [
  "India & ME",
  "Americas - Banking, Financial Services & Insurance",
  "Europe",
  "Americas - Retail & Consumer Packaged Goods (RCG)",
  "Americas - Media & Entertainment (M&E)",
  "Americas - Travel, Transport & Hospitality (TTH)",
  "Americas - Life Sciences",
  "Americas - Hi-Tech",
  "Americas - Insurance 1 (INS1)",
  "South Africa",
  "Americas - Manufacturing",
  "Americas - Banking & Financial Services - 1 (BFS1)",
  "Nordics",
  "Americas - Energy",
  "Americas - Utilities",
  "Asia Pacific & Japan (APJ)",
  "Microsoft",
  "OTHERS",
  "Americas - Health",
  "Syncordis",
  "N+P",
  "LTIFST",
];

export const daysData = [
  "Not Due",
  "Due in Current Month",
  "0 - 10 days",
  "11 - 30 days",
  "31 - 60 days",
  "61 - 90 days",
  "91 - 180 days",
  "181 - 365 days",
  "365+ days",
];
